deployments:
  - name: taxi_local_data
    entrypoint: 03-orchestration/3.4/orchestrate.py:main_flow
    work_pool:
      name: zoompool
  - name: taxi_download_data
    entrypoint: 03-orchestration/3.5/orchestrate_download.py:main_flow_download
    work_pool:
      name: zoompool
