version: "3.3"
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      SERVICES: s3
      AWS_DEFAULT_REGION: eu-west-1
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: admin
      DEFAULT_REGION: eu-west-1
    ports:
      - 4566:4566
