# Docker multistage build to reduce image size
FROM python:3.10.8-slim AS build
RUN python -m venv /opt/venv
# Make sure we use the virtualenv:
ENV PATH="/opt/venv/bin:$PATH"

RUN apt-get update && \
    apt-get install -y libmariadb-dev && \
    apt-get install -y gcc
RUN pip install mlflow psycopg2-binary mysqlclient google-cloud-storage

FROM python:3.10.8-slim
COPY --from=build /opt/venv /opt/venv
COPY --from=build /usr/lib /usr/lib
# Make sure we use the virtualenv:
ENV PATH="/opt/venv/bin:$PATH"
EXPOSE 5000/tcp
ENTRYPOINT [ "mlflow", "server", "--host", "0.0.0.0"]
CMD [ "--backend-store-uri", "sqlite:////mlruns/mlruns.db", \
      "--default-artifact-root", "/mlartifacts"]