version: "3.9"
services:
  jupyterlab:
    build: .
    container_name: mlops-zoomcamp-jupyter
    ports:
      - 8888:8888
    volumes:
      - "../data:/home/jovyan/data"
      - "..:/home/jovyan/work"
      - "../mlflow/mlartifacts:/mlartifacts"
    environment:
      - PYTHONPATH=$PYTHONPATH:/home/jovyan/work/src
      - DATA_DIR=/home/jovyan/data
      - JUPYTER_ENABLE_LAB=yes
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MODELS_DIR=/mlartifacts
    entrypoint: start-notebook.sh --NotebookApp.token="" --NotebookApp.notebook_dir=/home/jovyan/work
    networks:
      - net

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile-mlflow
    container_name: mlops-zoomcamp-mlflow
    ports:
      - 5000:5000
    volumes:
      - "../mlflow/mlruns:/mlruns"
      - "../mlflow/mlartifacts:/mlartifacts"
    networks:
      - net

  prefect-db:
    image: postgres:15.2-alpine
    container_name: mlops-zoomcamp-prefect-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prefect
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
    profiles: ["prefect-server"]
    networks:
      - net

  minio:
    image: minio/minio:latest
    container_name: mlops-zoomcamp-minio
    entrypoint:
      [
        "minio",
        "server",
        "--address",
        "0.0.0.0:9000",
        "--console-address",
        "0.0.0.0:9001",
        "/data",
      ]
    volumes:
      - "minio:/data"
    ports:
      - 9000:9000
      - 9001:9001
    profiles: ["minio"]
    networks:
      - net

  prefect-server:
    image: prefecthq/prefect:2.10.7-python3.10
    container_name: mlops-zoomcamp-prefect-server
    restart: always
    volumes:
      - prefect:/root/.prefect
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "server", "start"]
    environment:
      # If you want to access Prefect Server from anywhere other than the Docker host machine, you will need to change
      # PREFECT_UI_URL to match the external hostname/IP used to load the  UI in your web browser.
      - PREFECT_UI_URL=http://127.0.0.0:4200/api
      - PREFECT_API_URL=http://127.0.0.1:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@prefect-db:5432/prefect
      # Uncomment the following line if you want to use the 'S3 Bucket' storage block instead of the older 'S3' storage
      # - EXTRA_PIP_PACKAGES=prefect-aws
    ports:
      - 4200:4200
    depends_on:
      - database
    profiles: ["prefect-server"]
    networks:
      - net

  prefect-agent:
    image: prefecthq/prefect:2.10.7-python3.10
    container_name: mlops-zoomcamp-prefect-agent
    restart: always
    entrypoint: ["prefect", "agent", "start", "-q", "YOUR_WORK_QUEUE_NAME"]
    environment:
      - PREFECT_API_URL=http://server:4200/api
    #       Use PREFECT_API_KEY if connecting the agent to Prefect Cloud
    #     - PREFECT_API_KEY=YOUR_API_KEY
    profiles: ["prefect-agent"]
    networks:
      - net

  prefect-cli:
    build:
      context: .
      dockerfile: Dockerfile-prefect
    container_name: mlops-zoomcamp-prefect-cli
    entrypoint: " tail -f /dev/null"
    working_dir: "/root/03-orchestration"
    volumes:
      - "../03-orchestration:/root/03-orchestration"
      - "../data:/data"
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
    #       Use PREFECT_API_KEY to use the CLI to interact with Prefect Cloud
    #     - PREFECT_API_KEY=YOUR_API_KEY
    profiles: ["prefect-cli"]
    networks:
      - net

volumes:
  prefect:
  db:
  minio:

networks:
  net:
    name: net
    driver: bridge
